/**
 * Writes .env.localdb, pointing the app at the Supabase stack running on this machine.
 *
 * Run it after `supabase start`, then `npm run dev:local`.
 *
 * -- Why a separate file rather than editing .env.local -------------------------------------------
 *
 * .env.local is the cloud project, and it holds the service role key the live check scripts need.
 * Swapping it back and forth to try something locally is how you end up running a "local" test
 * against production, or pasting the wrong key back afterwards.
 *
 * Vite loads .env.[mode] AFTER .env.local and lets it win, so `vite --mode localdb` reads this file
 * on top of that one and nothing else has to change. `npm run dev` still means the cloud; only
 * `npm run dev:local` means this. Both are gitignored by the .env.* rule.
 *
 * -- Why generated rather than committed ----------------------------------------------------------
 *
 * The local anon key is not a constant. It has changed format across CLI versions - a demo JWT once,
 * an sb_publishable_ string now - so a hard-coded one works until the day it silently doesn't, and
 * the symptom is an app that loads and then fails every request. Asking the CLI is always right.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(root, ".env.localdb");

/** `supabase status -o env` prints KEY="value" lines. Tolerates unquoted values too. */
function readStatus() {
  let raw;
  try {
    raw = execFileSync("npx", ["--yes", "supabase@latest", "status", "-o", "env"], {
      cwd: root,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
      shell: process.platform === "win32",
    });
  } catch (err) {
    const detail = `${err.stderr ?? ""}${err.stdout ?? ""}`.trim();
    throw new Error(
      "Couldn't read the local Supabase status.\n\n" +
        "Start it first:\n" +
        "  1. Launch Docker Desktop and wait for it to say it's running\n" +
        "  2. npm run local:up\n" +
        (detail ? `\nThe CLI said:\n${detail}\n` : "")
    );
  }

  const env = {};
  for (const line of raw.split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*"?(.*?)"?\s*$/);
    if (m) env[m[1]] = m[2];
  }
  return env;
}

/** Anything in .env.local that isn't a Supabase endpoint is still wanted locally. */
function carriedOver() {
  const path = join(root, ".env.local");
  if (!existsSync(path)) return {};
  const keep = {};
  for (const line of readFileSync(path, "utf8").split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (m && m[1] === "VITE_TWITCH_CLIENT_ID") keep[m[1]] = m[2];
  }
  return keep;
}

const status = readStatus();
const missing = ["API_URL", "ANON_KEY", "SERVICE_ROLE_KEY"].filter((k) => !status[k]);
if (missing.length) {
  throw new Error(
    `The CLI reported no ${missing.join(", ")}. That usually means the stack is not up yet - ` +
      "run `npm run local:up` and try again."
  );
}

const twitch = carriedOver();
const body = [
  "# GENERATED by scripts/local-env.mjs - regenerate rather than edit.",
  "# The Supabase stack running on this machine. Used only by `npm run dev:local`.",
  "#",
  "# These keys are local-only and reset with the container. They are not secrets in the sense the",
  "# cloud project's are, but the file is gitignored anyway by the .env.* rule.",
  "",
  `VITE_SUPABASE_URL=${status.API_URL}`,
  `VITE_SUPABASE_ANON_KEY=${status.ANON_KEY}`,
  "",
  "# For the read-write check scripts, which need to clean up after themselves. Note they read",
  "# .env.local rather than this file - see supabase/README.md.",
  `SUPABASE_SERVICE_ROLE_KEY=${status.SERVICE_ROLE_KEY}`,
  "",
  ...(twitch.VITE_TWITCH_CLIENT_ID
    ? [
        "# Carried over from .env.local. Twitch login needs a redirect URI registered for localhost",
        "# on the Twitch console, so it may not work locally even with this set.",
        `VITE_TWITCH_CLIENT_ID=${twitch.VITE_TWITCH_CLIENT_ID}`,
      ]
    : []),
  "",
].join("\n");

writeFileSync(OUT, body);

console.log(`wrote ${OUT}`);
console.log(`  API      ${status.API_URL}`);
console.log(`  Studio   ${status.STUDIO_URL ?? "http://127.0.0.1:54323"}`);
console.log(`  Database ${status.DB_URL ?? "postgresql://postgres:postgres@127.0.0.1:54322/postgres"}`);
console.log("\nNow: npm run dev:local");
